// File containing a collection of enums

export class AccountType {
  ADMIN = "ADMIN";
  COACH = "COACH";
  PARENT = "PARENT";
  NONE = null;
}

export class EventStatus {
  SCHEDULED = "SCHEDULED";
  CANCELLED = "CANCELLED";
}

export class NotificationType {
  MESSAGERECEIVED = "MESSAGERECEIVED";
  PLAYERPOSTUPDATED = "PLAYERPOSTUPDATED";
  SELECTEDFORPLAYERPOST = "SELECTEDFORPLAYERPOST";
  UNSELECTEDFORPLAYERPOST = "UNSELECTEDFORPLAYERPOST";
  PLAYERPOSTDELETED = "PLAYERPOSTDELETED";
  PLAYERPOSTCLOSED = "PLAYERPOSTCLOSED";
  MATCHPOSTUPDATED = "MATCHPOSTUPDATED";
  SELECTEDFORMATCHPOST = "SELECTEDFORMATCHPOST";
  UNSELECTEDFORMATCHPOST = "UNSELECTEDFORMATCHPOST";
  MATCHPOSTDELETED = "MATCHPOSTDELETED";
  MATCHPOSTCLOSED = "MATCHPOSTCLOSED";
  EVENTCREATED = "EVENTCREATED";
  EVENTUNSCHEDULED = "EVENTUNSCHEDULED";
  EVENTSCHEDULED = "EVENTSCHEDULED";
}
